name: docker
kind: pipeline
type: docker
image_pull_secrets: [GLO_DOCKER_HUB]
steps:
  - name: docker-build-push
    image: findusproptech/fpt-drone-cli
    environment:
      DOCKER_USERNAME:
        from_secret: GLO_DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: GLO_DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - |
        while true; do
          # Check if Docker is running
          docker info > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "Docker is up and running!"
            break
          else
            echo "Waiting for Docker to start..."
          fi
          # Wait for 3 seconds before checking again
          sleep 3
        done
      - export VERSION=$(cat VERSION)
      - echo $VERSION
      - docker build -t findusproptech/drone-volume-cache:$VERSION .

services:
  - name: svc-docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
