name: docker
kind: pipeline
type: docker
image_pull_secrets: [GLO_DOCKER_HUB]
steps:
  - name: docker-build-push
    image: findusproptech/fpt-drone-cli
    environment:
      DOCKER_USERNAME:
        from_secret: GLO_DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: GLO_DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - |
        # Initialize counter for retry attempts
        COUNTER=0
        # Maximum number of attempts to check Docker status
        MAX_RETRIES=10

        while [ $COUNTER -lt $MAX_RETRIES ]; do
          # Check if Docker is running
          docker info > /dev/null 2>&1
          EXIT_CODE=$?
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "Docker is up and running!"
            break
          else
            echo "Attempt ${COUNTER}: Waiting for Docker to start... (Exit code: $EXIT_CODE)"
          fi

          # Increment counter
          let COUNTER=COUNTER+1

          # Wait for 3 seconds before checking again
          sleep 3
        done

        if [ $COUNTER -eq $MAX_RETRIES ]; then
          echo "Failed to start Docker after ${MAX_RETRIES} attempts."
          exit 1
        fi
        echo done
      - export VERSION=$(cat VERSION)
      - echo $VERSION
      - docker build -t findusproptech/drone-volume-cache:$VERSION .

services:
  - name: svc-docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
